apiVersion: v1
kind: ConfigMap
metadata:
  name: autocad-mcp-config
  namespace: autocad-mcp
  labels:
    app: autocad-mcp-server
data:
  app-config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 300
    
    logging:
      level: "INFO"
      format: "json"
      file: "/app/logs/autocad-mcp.log"
      max_size: "100MB"
      backup_count: 5
    
    rate_limiting:
      enabled: true
      session_limit: 100
      tool_limits:
        ai_features: 5
        code_generation: 10
        testing: 20
        debugging: 15
        inspection: 30
        general: 50
    
    security:
      scanning_enabled: true
      audit_logging: true
      encryption_enabled: true
      session_timeout: 3600
    
    performance:
      caching:
        enabled: true
        ttl: 3600
        max_size: "256MB"
      monitoring:
        enabled: true
        metrics_endpoint: "/metrics"
    
    features:
      ai_assistance: true
      collaboration: true
      advanced_debugging: true
      enterprise_features: true
  
  nginx.conf: |
    upstream autocad_mcp {
        server autocad-mcp-service:80;
    }
    
    server {
        listen 80;
        server_name _;
        
        location /health {
            access_log off;
            return 200 "healthy\n";
        }
        
        location / {
            proxy_pass http://autocad_mcp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_connect_timeout 30s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
            
            client_max_body_size 50M;
        }
    }